title: lookitskyle with Cocktails
description: ""
footer_text: Copyright 2021 | Kyle Garrett
header_feature_image: ../uploads/books4screen.jpg
header_text: lookitskyle with Cocktails
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
